name: Build MedicalLabAnalyzer for All Platforms

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-windows:
    runs-on: windows-server-2025
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build Windows x64
      run: dotnet build -c Release --no-restore
    
    - name: Publish Windows x64
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -o publish/windows
    
    - name: Create Windows ZIP
      run: |
        Compress-Archive -Path "publish/windows/*" -DestinationPath "MedicalLabAnalyzer-Windows-x64.zip"
    
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MedicalLabAnalyzer-Windows-x64
        path: MedicalLabAnalyzer-Windows-x64.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libgdiplus
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build Linux x64
      run: dotnet build -c Release --no-restore
    
    - name: Publish Linux x64
      run: dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -o publish/linux
    
    - name: Make executable
      run: chmod +x publish/linux/MedicalLabAnalyzer
    
    - name: Create Linux TAR.GZ
      run: tar -czf MedicalLabAnalyzer-Linux-x64.tar.gz -C publish/linux .
    
    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MedicalLabAnalyzer-Linux-x64
        path: MedicalLabAnalyzer-Linux-x64.tar.gz

  build-macos:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build macOS x64
      run: dotnet build -c Release --no-restore
    
    - name: Publish macOS x64
      run: dotnet publish -c Release -r osx-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -o publish/macos
    
    - name: Make executable
      run: chmod +x publish/macos/MedicalLabAnalyzer
    
    - name: Create macOS TAR.GZ
      run: tar -czf MedicalLabAnalyzer-macOS-x64.tar.gz -C publish/macos .
    
    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MedicalLabAnalyzer-macOS-x64
        path: MedicalLabAnalyzer-macOS-x64.tar.gz

  build-macos-arm64:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build macOS ARM64
      run: dotnet build -c Release --no-restore
    
    - name: Publish macOS ARM64
      run: dotnet publish -c Release -r osx-arm64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -o publish/macos-arm64
    
    - name: Make executable
      run: chmod +x publish/macos-arm64/MedicalLabAnalyzer
    
    - name: Create macOS ARM64 TAR.GZ
      run: tar -czf MedicalLabAnalyzer-macOS-ARM64.tar.gz -C publish/macos-arm64 .
    
    - name: Upload macOS ARM64 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MedicalLabAnalyzer-macOS-ARM64
        path: MedicalLabAnalyzer-macOS-ARM64.tar.gz

  build-docker:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: docker build -t medicallab-analyzer:latest .
    
    - name: Upload Docker Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MedicalLabAnalyzer-Docker
        path: medicallab-analyzer:latest

  create-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-macos, build-macos-arm64]
    if: github.event_name == 'release'
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Create Release Assets
      run: |
        mkdir -p release-assets
        cp artifacts/MedicalLabAnalyzer-Windows-x64/MedicalLabAnalyzer-Windows-x64.zip release-assets/
        cp artifacts/MedicalLabAnalyzer-Linux-x64/MedicalLabAnalyzer-Linux-x64.tar.gz release-assets/
        cp artifacts/MedicalLabAnalyzer-macOS-x64/MedicalLabAnalyzer-macOS-x64.tar.gz release-assets/
        cp artifacts/MedicalLabAnalyzer-macOS-ARM64/MedicalLabAnalyzer-macOS-ARM64.tar.gz release-assets/
    
    - name: Upload Release Assets
      uses: actions/upload-artifact@v4
      with:
        name: Release-Assets
        path: release-assets/