name: Quick Test Build

on:
  workflow_dispatch:  # للاختبار اليدوي
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  quick-test:
    name: Quick Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Debug Environment
      run: |
        echo "OS: ${{ runner.os }}"
        echo "Platform: ${{ runner.arch }}"
        echo "Dotnet version: $(dotnet --version)"
        echo "Working directory: $(pwd)"
        echo "Files in directory:"
        ls -la
    
    - name: Check Project Files
      run: |
        echo "Checking project structure..."
        if [ -f "MedicalLabAnalyzer.csproj" ]; then
          echo "✅ Project file found"
          cat MedicalLabAnalyzer.csproj
        else
          echo "❌ Project file not found"
          find . -name "*.csproj" -type f
        fi
    
    - name: Restore dependencies
      run: dotnet restore --verbosity normal
    
    - name: Build
      run: dotnet build --configuration Release --no-restore --verbosity normal
    
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal || echo "⚠️ Tests failed, but build succeeded"
    
    - name: Build artifacts info
      run: |
        echo "Build completed successfully!"
        echo "Output directory: $(pwd)/bin/Release"
        if [ -d "bin/Release" ]; then
          ls -la bin/Release/
        else
          echo "❌ Output directory not found"
        fi
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: quick-build-output
        path: bin/Release/
        retention-days: 7